#########################################################################
# Title:         Cloudbox: Nginx-Proxy | Letsencrypt Tasks              #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Letsencrypt | Stop and remove any existing container
  docker_container:
    name: letsencrypt
    state: absent

- name: Letsencrypt | HTTP Validation
  import_tasks: "http_validation.yml"
